# Jekyll Site Settings

tite: Lauren N. Murphy | Site
name: 'Lauren Murphy'
description: "I'm a developer-in-training. This is my personal website."
baseurl: ""
url: "http://laurennor.github.io"
twitter_username: laurennor
github_username: laurennor

# Build Settings
markdown: kramdown
hightlighter: pygments
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed